"""Golden regression test: 160 hand-annotated citations (plan A17).

Each entry is ``(ref_wikitext, main_def_wikitext_or_None, expected_types,
expected_page, expected_pages, expected_located_pages, note)``. Repeated refs
(main_def present) are resolved with :func:`resolve_references` against a
two-ref mini-article, matching the pipeline's name inheritance.

Source: data/annotations/parser_validation_sample.csv (2014-11-06 + 2026-01-01,
stratified sample, seed 42). A few rows carry a note: they are malformed-source
citations where the accepted behaviour keeps the parser's value instead of the
human gold (the value is asserted against the parser to lock it in).
"""

from wikiloc.parser import (
    parse,
    resolve_references,
    _ref_from_wikitext,
    compute_located_pages,
)
from wikiloc.constants import LOC_PARAMS

CANON = {
    "page": "page", "p": "page",
    "pages": "pages", "pp": "pages",
    "at": "at", "loc": "at",
    "quote": "quote", "q": "quote", "quotation": "quote",
    "quote-page": "quote", "quotepage": "quote", "qp": "quote", "quotation-page": "quote",
    "quote-pages": "quote", "quotepages": "quote", "qpp": "quote", "quotation-pages": "quote",
    "quote-location": "quote", "quote-loc": "quote", "quotation-location": "quote", "quote-at": "quote",
    "chapter": "chapter", "contribution": "chapter", "section": "chapter",
    "sections": "chapter", "entry": "chapter", "article": "chapter",
    "department": "other", "time": "other", "minutes": "other",
    "season": "other", "series-no": "other", "level": "other", "scene": "other",
    "sheet": "other", "sheets": "other", "inset": "other",
    "opinion": "other", "pinpoint": "other",
}

LOCATOR_COLS = {c for cols in LOC_PARAMS["en"].values() for c in cols}

GOLD = [
    ("<ref>{{cite book |last=Salkie |first=Raphael |chapter=Outside the 'Free World' |title=The Chomsky Update: Linguistics and Politics |publisher=Unwin Hyman |year=1990 |page=174 |isbn=0-04-445589-5}}</ref>", None, 'chapter,page', '174', '', 1, ''),
    ('<ref>\r\n{{Cite book\r\n | author      = Wodehouse, P. G.\r\n | year        = 1969 <!--published 1969, written 1968, "fifty-three years ago" after 1915-->\r\n | chapter     = Preface [new since the 1969 edition]\r\n | title       = Something Fresh\r\n | quote       = \'\'Something Fresh\'\' was the first of what I might call – in fact, I will call – the Blandings Castle Saga.\r\n | authorlink       = P. G. Wodehouse\r\n}}\r\n</ref>', None, 'chapter,quote', '', '', None, ''),
    ("<ref>{{cite book|last=Weekes|first=Don|title=The Best and Worst of Hockey's Firsts: The Unofficial Guide|year=2003|publisher=Greystone Books|location=Canada|isbn=9781550548600|pages=240}}</ref>", None, 'pages', '', '240', 1, ''),
    ('<ref name="Kent">{{cite book|url=http://www.austchartbook.com.au/pages/book1970-1992.htm|title=Australian Chart Book 1970–1992|format=doc|last=Kent|first=David|authorlink=David Kent (historian)|publisher=Australian Chart Book, St Ives, N.S.W |year=1993|isbn=0-646-11917-6}}</ref>', None, '', '', '', None, ''),
    ('<ref name="British Hit Singles & Albums">{{cite book\r\n| first= David\r\n| last= Roberts\r\n| year= 2006\r\n| title= British Hit Singles & Albums\r\n| edition= 19th\r\n| publisher= Guinness World Records Limited \r\n| location= London\r\n| isbn= 1-904994-10-5\r\n| page= 264}}</ref>', None, 'page', '264', '', 1, ''),
    ("<ref name='Whittington'/>", "<ref name='Whittington'>{{cite book |author=H. B. Whittington ''et al.'' |title=Treatise on Invertebrate Paleontology. Part O, Revised. Trilobita |chapter=Introduction, Order Agnostida, Order Redlichiida |year=1997}}</ref>", 'chapter', '', '', None, ''),
    ('<ref>{{cite book|last=Meeks|first=G.|author2=Meeks, J.G.|title=Towards a cost-benefit analysis of accounting regulation|year=2002|publisher=Institute of Chartered Accountants in England and Wales|location=London|isbn=1841521035}}</ref>', None, '', '', '', None, ''),
    ('<ref>{{cite book|author=Counihan, Carrie|title=Food in the USA|url=http://books.google.com/?id=9nzLJoRXymQC&pg=RA2-PA191|year=2002|publisher=Routledge via Google Books|pages=191|isbn=0-415-93232-7|accessdate=2009-05-09}}</ref>', None, 'pages', '', '191', 1, ''),
    ('<ref name=taylor/>', '<ref name=taylor>{{cite book|last=Taylor|first=Peter|title=Brits: The War Against the IRA|year=2001|publisher=Bloomsbury Publishing|page=303 |quote=On 26 October 1989, two IRA gunmen with automatic weapons opened fire on a car at [[Wildenrath]], in Germany, as it stopped at a petrol station snack bar. The driver, Corporal Maheshkumar Islania, was not a soldier but a member of the [[Royal Air Force]], supervising the RAF communications centre at Wildenrath. Corporal Islania tried to drive away but was pursued by the gunmen, firing repeatedly. He was not alone in the car. With him was his wife and six-month-old baby daughter, Nivruti Mahesh. She was shot once through the head and became one of the youngest victims to die in the conflict. Her father was hit many times. Her mother survived, although in deep shock.}}</ref>', 'page,quote', '303', '', 1, ''),
    ('<ref name="Ilmi" />', '<ref name=Ilmi>{{cite book|last=Qazi|first=Mrs. Rifat|title={{nq{{!}}سرمایۂ اُردُو (لازمی){{rlm}}}}|year=2008|publisher=Ilmi Kitab Khana|location=Kabir St., Urdu Bazaar, Lahore 54 000|page=133|url=http://ilmikitabkhana.com/store/ilmi-Books-Urdu/Urdu-fsc/isurp2fedb-ilmi-sarmaya-urdu-part-2-federal-board-rifat-qazi-fa-fsc-ics-icom-urdu}}</ref>', 'page', '133', '', 1, ''),
    ('<ref>{{Cite book |last=Symonds |first=Craig L. |title=The Civil War at Sea |year=2012 |publisher=Oxford University Press |isbn=978-0-19-993168-2 |location=New York |page=110}}</ref>', None, 'page', '110', '', 1, ''),
    ('<ref>{{cite book |title=Baseball Hall of Shame |last=Nash |first=Bruce |author2=Zullo, Allan  |year=1989 |publisher=Simon and Schuster |isbn=0-671-68766-2 |page=46 |url=https://books.google.com/books?id=QtX4CreRGNEC&q=%22Vic+Delmore%22&pg=PT41}}</ref>', None, 'page', '46', '', 1, ''),
    ('<ref>{{Cite book | doi=10.1109/NANOMED.2010.5749842| chapter=Controlled chemical functionalization of water-soluble nanoprobes for site-specific biomedical diagnosis| title=2010 IEEE International Conference on Nano/Molecular Medicine and Engineering| pages=235–238| year=2010| last1=Kim| first1=Jeong-Hwan| last2=Kim| first2=Jin-Woo| isbn=978-1-61284-152-6| s2cid=21639971}}</ref>', None, 'chapter,pages', '', '235–238', 4, ''),
    ('<ref name="Ramblers">{{cite book|url= https://es.scribd.com/document/588993104/Gonzalo-Planet-Se-oyen-los-pasos|title=Se oyen los pasos|publisher=Beatguru Libros|isbn=978-9562991001|first=Gonzalo|last=Planet|language=es|date=2004|access-date=April 16, 2025|quote=Es el disco más vendido de la historia de Chile", dice el productor. "Debe haber superado las seiscientas mil copias vendidas.|page=21}}</ref>', None, 'page,quote', '21', '', 1, ''),
    ('<ref name=":2">{{Cite book |url=https://nap.nationalacademies.org/read/610/chapter/9 |title=Read "Women\'s Work, Men\'s Work: Sex Segregation on the Job" at NAP.edu |language=en |chapter=Appendix B: Biographical Sketches of Committee Members and Staff}}</ref>', None, 'chapter', '', '', None, ''),
    ('<ref name="lovrenovic-naklada-ljevak.hr">{{cite book |last1=Lovrenović |first1=Dubravko |title=Na klizištu povijesti : sveta kruna ugarska i sveta kruna bosanska 1387-1463 |date=2006 |publisher=Synopsis |location=Sarajevo |isbn=953-7035-09-3 |url=http://www.naklada-ljevak.hr/knjiga.asp?isbn=953-7035-09-3 |accessdate=10 June 2018}}</ref>', None, '', '', '', None, ''),
    ('<ref name=Nolan/>', '<ref name=Nolan>{{cite book |last=Nolan |first=Thomas Brennan |authorlink=Thomas Brennan Nolan |title=Memorial to Henry Gardiner Ferguson, 1882-1966 |url=https://books.google.com/books?id=BacpAQAAIAAJ |year=1966 |publisher=[[Geological Society of America]]}}</ref>', '', '', '', None, ''),
    ('<ref>{{cite book |last1=Matt |first1=Alphons |title=Zwischen allen Fronten : Der Zweite Weltkrieg aus der Sicht des Büros Ha. |date=1969 |publisher=Frauerfeld und Stuttgart |location=Huber |pages=180–182 |language=de|oclc=480334587}}</ref>', None, 'pages', '', '180–182', 3, ''),
    ('<ref name=":2" />', '<ref name=":2">{{Cite book |last1=Futhey |first1=John Smith |url=http://archive.org/details/cu31924005813518 |title=History of Chester County, Pennsylvania, with Genealogical and Biographical Sketches |last2=Cope |first2=Gilbert |publisher=Louis H. Everts |year=1881 |location=Philadelphia |pages=727–728 |language=en-US}}</ref>', 'pages', '', '727–728', 2, ''),
    ('<ref>{{Cite book |title=La Floresta Española Peruana |last=Monterola |first=J. M. |publisher=[[El Comercio (Peru)|Imprenta del Comercio]] |year=1848 |pages=52 |language=es |url=https://books.google.com/books?id=NWRZAAAAcAAJ |quote=Por Suprema resolucion de la Junta, se suprimió la Intendencia de Lima, que la servia D. Juan María Galvez, [...]}}</ref>', None, 'pages,quote', '', '52', 1, ''),
    ('<ref name="Bohr 1913 476"/>', '<ref name="Bohr 1913 476">{{cite journal\r\n| last=Bohr | first=Niels\r\n| title=On the Constitution of Atoms and Molecules\r\n| journal=Philosophical Magazine | year=1913\r\n| volume=26 | issue=1 | page=476\r\n|url=http://www.chemteam.info/Chem-History/Bohr/Bohr-1913a.html\r\n| bibcode=1914Natur..93..268N\r\n| doi=10.1038/093268a0}}</ref>', 'page', '476', '', 1, ''),
    ('<ref>{{cite journal |title = A Survey of New England: A Concentration of Talent |journal=The Economist |date=August 8, 1987 |quote=MIT for a long time... stood virtually alone as a university that embraced rather than shunned industry.}}</ref>', None, 'quote', '', '', None, ''),
    ('<ref name="pmid9459649">{{cite journal | author = De Broe ME, Elseviers MM | title = Analgesic nephropathy | journal = [[New England Journal of Medicine]] | volume = 338 | issue = 7 | pages = 446–52 | date = February 1998 | pmid = 9459649 | doi = 10.1056/NEJM199802123380707 | issn = 0028-4793 }}</ref>', None, 'pages', '', '446–52', 7, ''),
    ('<ref>{{cite journal |last1= Donner |first1= Michael B. |last2= VandeCreek |first2= Leon |last3= Gonsiorek |first3= John C. |last4= Fisher |first4= Celia B. |title= Balancing confidentiality: Protecting privacy and protecting the public |url= http://faculty.winthrop.edu/armisteadl/SchoolPsychologyResources/attachments/Donner_et_al_Balancin.pdf |journal= [[Professional Psychology: Research and Practice]] |department= Focus on Ethics |year= 2008 |volume= 39 |issue= 3 |pages= 369–76 |doi= 10.1037/0735-7028.39.3.369}}</ref>', None, 'pages', '', '369–76', 8, ''),
    ("<ref>{{Cite journal |last1=Stein |first1=Lorin |authorlink=Lorin Stein |date=December 2010 |title=New Books: ''Dickinson: Selected Poems and Commentaries'' |journal=Harper's |publisher=Harper's Magazine Foundation |volume=321 |issue=1,927 |page=75 |url=http://www.harpers.org/archive/2010/12/0083228 |accessdate=2011-01-22 |quote=Helen Vendler is... the reigning doyenne of American poetry criticism}}</ref>", None, 'page,quote', '75', '', 1, ''),
    ('<ref>{{cite journal |title=European CEO - Global Business Education Awards 2012|url=http://www.europeanceo.com/home/award-winners/2013/04/global-business-education-awards-2012/|journal= http://www.europeanceo.com}}</ref>', None, '', '', '', None, ''),
    ('<ref name=Motor197005/>', '<ref name=Motor197005>{{cite journal| authorlink = Robert Ward| title = Licensed to drive| journal=Motor| page = pages 32|date = date 230 May 1970}}</ref>', 'page', 'pages 32', '', 1, "page value differs (gold='32')"),
    ('<ref name="Philanthropy Mag">{{cite journal|last=Zinsmeister|first=Karl|title=Spartan Donors|journal=Philanthropy|date=Spring 2011|url=http://www.philanthropyroundtable.org/topic/excellence_in_philanthropy/spartan_donors|accessdate=5 June 2012|authorlink=Karl Zinsmeister}}</ref>', None, '', '', '', None, ''),
    ('<ref>{{cite journal|last=Geiger|first=Daniel L.|author2=Christine E. Thacker|title=Molecular phylogeny of Vetigastropoda reveals non-monophyletic Scissurellidae,  Trochoidea, and Fissurelloidea|journal=Molluscan Research|volume=25|issue=1|pages=47–55|url=http://www.mapress.com/mr/content/v25/2005f/n1p055.pdf}}</ref>', None, 'pages', '', '47–55', 9, ''),
    ('<ref>{{cite journal |url=http://books.google.com/books?id=CfdIAAAAMAAJ&lpg=PA292 |title=Portland Camera Club |author=Frank Roy Fraprie |journal= American Amateur Photographer and Camera and Dark Room |volume=19 |date=June 1907}}</ref>', None, '', '', '', None, ''),
    ('<ref name=":2" />', '<ref name=":2">{{cite journal | vauthors = Parashar UD, Johnson H, Steele AD, Tate JE | title = Health Impact of Rotavirus Vaccination in Developing Countries: Progress and Way Forward | journal = Clinical Infectious Diseases | volume = 62 | issue = Suppl 2 | pages = S91–95 | date = May 2016 | pmid = 27059361 | doi = 10.1093/cid/civ1015 | veditors = Parashar UD, Tate JE| doi-access = free | pmc = 11343039 }}</ref>', 'pages', '', 'S91–95', 5, ''),
    ("<ref>{{cite journal |last= Dunnington |first=Benn |title=Editor's page |page=19 |journal=Info=64 |issue=7 |date=1985 }}</ref>", None, 'page', '19', '', 1, ''),
    ("<ref>{{cite journal | vauthors = Davies MJ, D'Alessio DA, Fradkin J, Kernan WN, Mathieu C, Mingrone G, Rossing P, Tsapas A, Wexler DJ, Buse JB | display-authors = 6 | title = Management of Hyperglycemia in Type 2 Diabetes, 2018. A Consensus Report by the American Diabetes Association (ADA) and the European Association for the Study of Diabetes (EASD) | journal = Diabetes Care | volume = 41 | issue = 12 | pages = 2669–2701 | date = December 2018 | pmid = 30291106 | pmc = 6245208 | doi = 10.2337/dci18-0033 | quote = patients with clinical CVD not meeting individualized glycemic targets while treated with metformin (or in whom metformin is contraindicated or not tolerated) should have an SGLT2 inhibitor or GLP-1 receptor agonist with proven benefit for cardiovascular risk reduction added }}</ref>", None, 'pages,quote', '', '2669–2701', 33, ''),
    ('<ref name="radio">{{cite journal| url = https://api.parliament.uk/historic-hansard/commons/1990/jul/19/radioactivity| title = Radioactivity| journal = Hansard| date = 19 July 1990| volume = 176| at = cc1278-84}}</ref>', None, 'at', '', '', None, ''),
    ("<ref>{{cite journal|url=http://www.boc-online.org/PDF/vol124/M%20P%20Adams.pdf|title=Extinct and endangered ('E&E') birds: a proposed list for collection catalogues|author1=Adams, M. P.|author2=Cooper, J. H.|author3=Collar, N. J.|year=2003|journal=Bull. B.O.C.|volume=123A|page=338|url-status=dead|archive-url=https://web.archive.org/web/20110722021410/http://www.boc-online.org/PDF/vol124/M%20P%20Adams.pdf|archive-date=2011-07-22}}</ref>", None, 'page', '338', '', 1, ''),
    ("<ref>{{cite journal | title = A global context for megadroughts in monsoon Asia during the past millennium|author= Ashish Sinhaa |date=January 2011 |quote= Although the relationship between climate and societal change is complex and not necessarily deterministic, the widespread societal changes across monsoon Asia between the mid 13th to 15th centuries, which include famines and significant political reorganization within India ([Dando, 1980], [Pant et al., 1993] and [Maharatna, 1996]), ''the collapse of the Yuan dynasty in China'' (Zhang et al., 2008); Rajarata civilization in Sri Lanka (Indrapala, 1971), and the Khmer civilization of [[Angkor Wat]] fame in Cambodia (Buckley et al., 2010), strongly suggest that the MMDs may have played a major contributing role in shaping these societal changes. |doi=10.1016/j.quascirev.2010.10.005 |volume=30 | issue =1–2 |journal=Quaternary Science Reviews |pages=47–62| bibcode = 2011QSRv...30...47S}}</ref>", None, 'pages,quote', '', '47–62', 16, ''),
    ('<ref name="SCI-20140124">{{cite journal |author=Various |title=Special Collection – Curiosity – Exploring Martian Habitability |url=https://www.science.org/action/doSearch?AllField=Curiosity+Mars|date=24 January 2014 |journal=[[Science (journal)|Science]] |access-date=24 January 2014 }}</ref>', None, '', '', '', None, ''),
    ('<ref name="Ta-Shma 2014" />', '<ref name="Ta-Shma 2014">{{cite journal|last1=Ta-Shma|first1=Amnon|last2=Zwick|first2=Uri|author2-link=Uri Zwick|title=Deterministic rendezvous, treasure hunts, and strongly universal exploration sequences|journal=ACM Transactions on Algorithms|date=April 2014|volume=10|issue=3|doi=10.1145/2601068|s2cid=10718957|at=12}}</ref>', 'at', '', '', None, ''),
    ('<ref name=":0">{{Cite journal|last=Moran|first=Reid|date=April 1960|title=Dudleya rigidiflora Rose Topotype (8194)|url=https://bajaflora.org/MoranPageDisplay.aspx?P=6092|journal=Reid Moran\'s Field Book|pages=6092|via=San Diego Natural History Museum}}</ref>', None, 'pages', '', '6092', 1, ''),
    ('<ref>{{cite journal |last1=Warrington |first1=James |title=Letter |journal=Manchester City News |date=14 February 1914 |volume=6}}</ref>', None, '', '', '', None, ''),
    ('<ref name="Melseimer_etal2009">\r\n{{cite news\r\n | author=C. Melsheimer, G. Heygster, N. Mathew and L. Toudal Pedersen\r\n | year=2009\r\n | title=Retrieval of Sea Ice Emissivity and Integrated Retrieval of Surface and Atmospheric Parameters over the Arctic from [[AMSR]]-E data| journal=J. of the Remote Sens. Soc. of Japan\r\n | volume=29\r\n | number=1\r\n | pages= 236–241\r\n}}</ref>', None, 'pages', '', '236–241', 6, ''),
    ('<ref>{{cite news |author= Daisy Nguyen |title=Bunless burgers old hat at In-N-Out |publisher=[[The Oakland Tribune]] |date=2004-03-26 |url=http://calbears.findarticles.com/p/articles/mi_qn4176/is_20040326/ai_n14571110 |accessdate=2007-06-17 |quote=In fact, it was customers who gave it the name \'\'protein style\'\'," said Carl Van Fleet, the company\'s vice president of planning. "They also created it, in a sense, when they began requesting it in the early 1970s...}}</ref>', None, 'quote', '', '', None, ''),
    ('<ref name="protest">{{Cite news|last=Ramsay |first=Alix|title=Ski team protests| publisher=The Times|at=Sport section |date=30 March 1992}}</ref>', None, 'at', '', '', None, ''),
    ('<ref>{{cite news|title=Deaths|newspaper=[[The Times]]|date=13 December 1947|page=1}}</ref>', None, 'page', '1', '', 1, ''),
    ('<ref name=gettingkicks />', '<ref name=gettingkicks>{{cite news|last=De La Mater|first=Benning W.|title=Getting their kicks|accessdate=14 June 2011|newspaper=Berkshire Eagle|date=26 August 2005|pages=A01, A04}}</ref>', 'pages', '', 'A01, A04', 2, ''),
    ('<ref>{{cite news|last=Jonze|first=Tim|date=February 8, 2013|url=http://www.guardian.co.uk/music/2013/feb/09/miguel-kaleidoscope-dream|title=Miguel: the slow-burn success of a new R&B superstar|newspaper=[[The Guardian]]|location=London|at=The Guide section, p. 10|accessdate=February 9, 2013|archiveurl=http://www.webcitation.org/6EJ0C8V70|archivedate=February 9, 2013|deadurl=no}}</ref>', None, 'at', '', '', None, ''),
    ('<ref>\r\n{{cite news \r\n| url         = http://www.therecord.com/news-story/2618753--waterloo-suresh-loses-legal-battle-over-terrorism-charges/\r\n| title       = ‘Waterloo Suresh’ loses legal battle over terrorism charges\r\n| publisher   = [[Kitchener-Waterloo Record]]\r\n| date        = 2012-12-14\r\n| accessdate  = 2013-07-20\r\n| archivedate = 2013-07-20\r\n| archiveurl  = http://www.webcitation.org/query?url=http%3A%2F%2Fwww.therecord.com%2Fnews-story%2F2618753--waterloo-suresh-loses-legal-battle-over-terrorism-charges%2F&date=2013-07-20\r\n| deadurl     = No \r\n| quote       =  Sriskandarajah and two other men — Piratheepan Nadarajah of Brampton and Momin Khawaja of Ottawa — challenged the constitutional validity of terrorism laws passed in the wake of 9/11 attacks in the U.S. But in unanimous rulings written by Chief Justice Beverley McLachlin, seven judges soundly rejected arguments the laws are too broad and improperly infringe on freedom of expression rights. \r\n}}\r\n</ref>', None, 'quote', '', '', None, ''),
    ('<ref>{{Cite news|work=Broadcasting|date=July 16, 1956|page=90|title=WAIM-TV Now ABC Affiliate|id={{ProQuest|1401215877}}|url=https://worldradiohistory.com/Archive-BC/BC-1956/1956-07-16-BC.pdf|access-date=February 18, 2023|archive-date=January 31, 2023|archive-url=https://web.archive.org/web/20230131030346/https://worldradiohistory.com/Archive-BC/BC-1956/1956-07-16-BC.pdf|url-status=live}}</ref>', None, 'page', '90', '', 1, ''),
    ('<ref name=":0" />', '<ref name=":0">{{Cite news |date=4 April 1889 |title=Obituary of Ker Baillie Hamilton |url=https://ufdc.ufl.edu/AA00079438/03113/zoom/2 |access-date=3 February 2025 |work=The Dominican |location=Dominica |quote=The death is announced of Mr. Ker Baillie Hamilton, C. B. on the 16th ultimo, at Broadwater Down, Tunbridge Wells}}</ref>', 'quote', '', '', None, ''),
    ('<ref name="ann-v7-kyoya"/>', '<ref name="ann-v7-kyoya">{{cite news | url=http://www.animenewsnetwork.com/review/ouran-high-school-host-club-gn-7 | title=Review: Ouran High School Host Club: G.novel 7 | work=[[Anime News Network]] | author=Carlo Santos | date=September 20, 2006| access-date=September 20, 2006| quote=Cool, calculating Kyoya ... }}</ref>', 'quote', '', '', None, ''),
    ('<ref name="nytimes"/>', '<ref name="nytimes">{{cite news |url=https://movies.nytimes.com/movie/100784/Mad-About-Music/details |archive-url=https://web.archive.org/web/20121017124729/http://movies.nytimes.com/movie/100784/Mad-About-Music/details |url-status=dead |archive-date=October 17, 2012 |department=Movies & TV Dept. |work=[[The New York Times]] |date=2012 |title=Mad About Music (1938) |access-date=December 10, 2008}}</ref>', '', '', '', None, ''),
    ('<ref name="cnn-bursztynsky-20200722">{{Cite news |last=Bursztynsky |first=Jessica |date=July 22, 2020 |title=Tesla will build its next Gigafactory near Austin, Texas |work=CNBC |department=Business News and Finance |url=https://www.cnbc.com/2020/07/22/tesla-will-build-its-next-gigafactory-near-austin-texas.html |url-status=live |access-date=July 26, 2020 |archive-url=https://web.archive.org/web/20210323145102/https://www.cnbc.com/2020/07/22/tesla-will-build-its-next-gigafactory-near-austin-texas.html |archive-date=March 23, 2021}}</ref>', None, '', '', '', None, ''),
    ('<ref name="Florida Today 13 August 1974">{{cite news |title=Obituary for Thomas D Bailey Bailey (Aged 76) |url=https://www.newspapers.com/clip/66130712/obituary-for-thomas-d-bailey-bailey/ |access-date=27 December 2020 |work=Florida Today |date=13 August 1974 |pages=4B}}{{Open Access}}</ref>', None, 'pages', '', '4B', None, "located_pages differs (gold=1)"),
    ('<ref name="auto6"/>', '<ref name="auto6">{{Cite news|url=https://www.newspapers.com/clip/115073366/north-county-times/|newspaper=[[North County Times]]|via=[[Newspapers.com]]|date=December 3, 1998|page=25, [https://www.newspapers.com/clip/115073505/north-county-times/ 29]|title=He\'s one Hall of a load|author=Courtney, Will}} {{Open access}}</ref>', 'page', '25, [https://www.newspapers.com/clip/115073505/north-county-times/ 29]', '', 1, "page value differs (gold='25')"),
    ('<ref>{{Cite news |date=1935-04-13 |title=Clubs Wielded at Anti-War Gathering |url=https://www.newspapers.com/article/daily-news-clubs-wielded-at-anti-war-gat/147841498/ |access-date=2024-05-22 |work=Daily News |pages=1}}</ref>', None, 'pages', '', '1', 1, ''),
    ("<ref>{{cite web|url=http://web.mit.edu/newsoffice/1999/johnson-0609.html |title=A tribute to MIT's Howard Johnson |first=David |last=Warsh |work=The Boston Globe |date=June 1, 1999 |accessdate=April 4, 2007 |quote=At a critical time in the late 1960s, [[Howard Wesley Johnson|Johnson]] stood up to the forces of campus rebellion at MIT. Many university presidents were destroyed by the troubles. Only [[Edward Levi]], [[University of Chicago]] president, had comparable success guiding his institution to a position of greater strength and unity after the turmoil.}}</ref>", None, 'quote', '', '', None, ''),
    ('<ref name="north prospect">{{cite web |url=http://digital.nls.uk/slezer/engraving.cfm?sl=58 |title=The North Prospect of the City of Edenburgh |department=Slezer\'s Scotland |website=[[National Library of Scotland]] |accessdate=2012-01-09}}</ref>', None, '', '', '', None, ''),
    ('<ref>{{cite web\r\n|title=The Ecology of the Lower Colorado River from Davis Dam to the Mexico-United States International Boundary: A Community Profile\r\n|url=http://www.nwrc.usgs.gov/techrpt/85-7-19.pdf\r\n|publisher=U.S. Fish and Wildlife Service\r\n|date=September 1988\r\n|first1=Robert D.\r\n|last1=Ohmart\r\n|first2=Bertin W.\r\n|last2=Anderson\r\n|first3=William C.\r\n|last3=Hunter\r\n|pages=9, 12, 14\r\n|format=PDF\r\n|accessdate=June 29, 2013}}</ref>', None, 'pages', '', '9, 12, 14', 3, ''),
    ('<ref name=Constitution>{{cite web |url=http://web.archive.org/web/20121101131446/http://www.constitution.bt/TsaThrim%20Eng%20%28A5%29.pdf |title=The Constitution of the Kingdom of Bhutan |work=[[Government of Bhutan]] |isbn=99936-754-0-7 |at=art.28}}</ref>', None, 'at', '', '', None, ''),
    ('<ref name="Frontier">{{cite web|url=http://data2.archives.ca/pdf/pdf001/p000000110.pdf |format= PDF|title= MG28, I 124 - Finding Aid No. 736  / Instrument de recherche no 736|work= Frontier College Fonds|publisher= [[National Archives of Canada]]|page= 418|year= 2003|accessdate= 2011-08-24}}</ref>', None, 'page', '418', '', 1, ''),
    ('<ref name="Coello"/>', '<ref name="Coello">\r\n{{cite web \r\n|url= http://www-wds.worldbank.org/servlet/WDSContentServer/WDSP/IB/1989/09/01/000009265_3960928071552/Rendered/PDF/multi_page.pdf\r\n|title=Two Irrigation Systems in Colombia\r\n|author=Plusquellec, Herve\r\n|publisher=The World Bank \r\n|year=1989\r\n|pages= 12–15\r\n|accessdate=2008-08-08}}</ref>', 'pages', '', '12–15', 4, ''),
    ('<ref>{{cite web|last=Olivier|first=Darren|title=Casualties in APCLS attack on MONUSCO/FARDC positions|url=http://www.africandefence.net/three-sandf-soldiers-wounded-by-apcls-attack-in-the-drc/|website=Africandefence.net|publisher=African Defence Review|accessdate=24 September 2014|date=1 May 2014|quote=The SANDF soldiers … stood their ground and defended their position with great courage and determination.}}</ref>', None, 'quote', '', '', None, ''),
    ('<ref>{{Cite web|date=August 11, 2021|title=Americans make use of their religious freedom|url=https://www.dallasnews.com/opinion/editorials/2021/08/11/americans-make-use-of-their-religious-freedom/|url-status=live|access-date=October 21, 2021|website=Dallas News|language=en|quote=Collin County scored slightly lower on the PRRI religious diversity scale than Dallas, but Collin County is 3% Hindu, 2% Muslim, and 2% Jewish, compared to 1% for those religions in Dallas County.|archive-url=https://web.archive.org/web/20210811133234/https://www.dallasnews.com/opinion/editorials/2021/08/11/americans-make-use-of-their-religious-freedom/ |archive-date=August 11, 2021 }}</ref>', None, 'quote', '', '', None, ''),
    ('<ref>{{Cite web |title=DART Gallery: A Collection of Public Art |url=https://dartorgcmsblob.dart.org/prod/docs/default-source/station-art/dartgallery.pdf |access-date=2024-06-09 |website=[[Dallas Area Rapid Transit]] |pages=20}}</ref>', None, 'pages', '', '20', 1, ''),
    ('<ref name=sinbad>{{cite web |last1=Anderson |first1=Aoife |title=Making waves: Sindbad heads new family in Corrie |url=https://www.britishnewspaperarchive.co.uk/viewer/BL/0001730/20070216/088/0017 |website=[[Evening Herald]] |access-date=2 September 2024 |pages=17 |date=16 February 2007|url-access=subscription|via=[[British Newspaper Archive]]}}</ref>', None, 'pages', '', '17', 1, ''),
    ('<ref name=":11">{{Cite web|last=Ministerie van Volksgezondheid|first=Welzijn en Sport|date=2018-06-07|title=De religieuze beleving van moslims in Nederland - Publicatie - Sociaal en Cultureel Planbureau|url=https://www.scp.nl/publicaties/publicaties/2018/06/07/de-religieuze-beleving-van-moslims-in-nederland|access-date=2021-03-07|website=www.scp.nl|page=77-79|language=nl-NL|format=PDF}}</ref>', None, 'page', '77-79', '', 3, ''),
    ("<ref>{{cite web | title = Severe Ancient Droughts: A Warning to California | url = https://www.nytimes.com/1994/07/19/science/severe-ancient-droughts-a-warning-to-california.html |author= William K. Stevens |work=[[The New York Times]]|access-date=15 August 2011 |date=19 July 1994 |quote= In medieval times the California droughts coincided roughly with a warmer climate in Europe, which allowed the Vikings to colonize Greenland and vineyards to grow in England, and with a severe dry period in South America, which caused the collapse of that continent's most advanced pre-Inca empire, the rich and powerful state of Tiwanaku, other recent studies have found.}}</ref>", None, 'quote', '', '', None, ''),
    ('<ref name="Census 2023"/>', '<ref name="Census 2023">{{Cite web|url=https://explore.data.stats.govt.nz/vis?fs[0]=2023%20Census%2C0%7CTotals%20by%20topic%23CAT_TOTALS_BY_TOPIC%23&pg=0&fc=Variable%20codes&bp=true&snb=9&df[ds]=ds-nsiws-disseminate&df[id]=CEN23_TBT_008&df[ag]=STATSNZ&df[vs]=1.0&dq=hq011%2Bhq010%2Bhq009%2Bhq008%2Bhq007%2Bhq006%2Bhq005%2Bhq004%2Bhq003%2Bhq002%2Bhq001%2Bhq000%2Bws1%2Bsp99%2Bra80%2Bra08%2Bra07%2Bra06%2Bra05%2Bra01%2Bra04%2Bra03%2Bra02%2Bra00%2Brb1%2Bls66%2Bls03%2Bls02%2Bls05%2Bls04%2Bls01%2Beg6%2Beg5%2Beg4%2Beg3%2Beg2%2Beg1%2BbiTotal%2Bbi0%2Bbi1%2BasTotalLG%2Bas4%2Bas3%2Bas2%2Bas1%2Bws4%2Bws3%2Bws2%2Bge3%2Bge2%2Bge1%2Brc%2BasMed%2BegTotal%2BlsTotal%2BgeTotal%2BrbTotal%2BraTotal%2BhqTotal%2BibTotal%2Bibmed%2BwsTotal.025.2013%2B2018%2B2023&to[TIME]=false&ly[rw]=CEN23_TBT_IND_003&ly[cl]=CEN23_YEAR_001|publisher=Stats NZ - Tatauranga Aotearoa - Aotearoa Data Explorer|access-date=3 October 2024|title=Totals by topic for individuals, (RC, TALB, UR, SA3, SA2, Ward, Health), 2013, 2018, and 2023 Censuses|at=Whakatane District (025)}}</ref>', 'at', '', '', None, ''),
    ('<ref name="Census 2023">{{Cite web|url=https://explore.data.stats.govt.nz/vis?fs[0]=2023%20Census%2C0%7CTotals%20by%20topic%23CAT_TOTALS_BY_TOPIC%23&pg=0&fc=Variable%20codes&bp=true&snb=9&df[ds]=ds-nsiws-disseminate&df[id]=CEN23_TBT_008&df[ag]=STATSNZ&df[vs]=1.0&dq=hq011%2Bhq010%2Bhq009%2Bhq008%2Bhq007%2Bhq006%2Bhq005%2Bhq004%2Bhq003%2Bhq002%2Bhq001%2Bhq000%2Bws1%2Bsp99%2Bra80%2Bra08%2Bra07%2Bra06%2Bra05%2Bra01%2Bra04%2Bra03%2Bra02%2Bra00%2Brb1%2Bls66%2Bls03%2Bls02%2Bls05%2Bls04%2Bls01%2Beg6%2Beg5%2Beg4%2Beg3%2Beg2%2Beg1%2BbiTotal%2Bbi0%2Bbi1%2BasTotalLG%2Bas4%2Bas3%2Bas2%2Bas1%2Bws4%2Bws3%2Bws2%2Bge3%2Bge2%2Bge1%2Brc%2BasMed%2BegTotal%2BlsTotal%2BgeTotal%2BrbTotal%2BraTotal%2BhqTotal%2BibTotal%2Bibmed%2BwsTotal.025.2013%2B2018%2B2023&to[TIME]=false&ly[rw]=CEN23_TBT_IND_003&ly[cl]=CEN23_YEAR_001|publisher=Stats NZ - Tatauranga Aotearoa - Aotearoa Data Explorer|access-date=3 October 2024|title=Totals by topic for individuals, (RC, TALB, UR, SA3, SA2, Ward, Health), 2013, 2018, and 2023 Censuses|at=Whakatane District (025)}}</ref>', None, 'at', '', '', None, ''),
    ('<ref name="Tucker"/>', '<ref name="Tucker">{{Cite web|author=Spencer Tucker|title=The Civil War Naval Encyclopedia|url=https://books.google.com/books?id=q4mwAtj2r3UC&dq=%22Ebenezer+Farrand%22+-wikipedia&pg=PA185|volume=1|date=2011|publisher=Greenwood Publishing Group|editor1=Paul G. Pierpaoli Jr.|page=185|access-date=January 24, 2022}}</ref>', 'page', '185', '', 1, ''),
    ('<ref name = "H142"/>', '<ref name = "H142">{{harvnb|Hopkins|1915|pp=142–3}}</ref>', 'pages', '', '142–3', 2, ''),
    ('<ref>{{harvnb|Kurzdorfer|2003|p=155}}</ref>', None, 'page', '155', '', 1, ''),
    ('{{harvs|txt|first=Sidney|last=Coleman|author1-link=Sidney Coleman|year=1973}}', None, '', '', '', None, ''),
    ('<ref name=lundry37>{{harvnb|Lundry|2009|p=37}}</ref>', None, 'page', '37', '', 1, ''),
    ('{{harv|Schmidt|1994|loc=Ch. 2.4}}', None, 'at', '', '', None, ''),
    ('{{harv|Schmidt|1994|loc=Lemma 2.3.2, p. 55}}', None, 'at', '', '', None, ''),
    ('<ref>{{harvnb|Cron|2002|pp=88–89}}</ref>', None, 'pages', '', '88–89', 2, ''),
    ('{{harvs|txt |authorlink=Émile Léonard Mathieu|first=Émile |last=Mathieu |year1=1861 |year2=1873}}', None, '', '', '', None, ''),
    ('<ref name=nagayama/>', '<ref name=nagayama>{{Harvnb|Nagayama|1997|pp=37–39|loc=(Wazamono list in Eng.-Japanese)}}</ref>', 'at,pages', '', '37–39', 3, ''),
    ('<ref>{{Harvnb|Matushevskaya|2013|p=8}}</ref>', None, 'page', '8', '', 1, ''),
    ('<ref name="grubb eit emissions projections"/>', '<ref name="grubb eit emissions projections">\r\n{{harvnb|Grubb|2003|pp=162–163}}\r\n</ref>', 'pages', '', '162–163', 2, ''),
    ('<ref>{{harvnb|Wills|2007|pp=115}}</ref>', None, 'pages', '', '115', 1, ''),
    ('<ref>{{harvnb|Robert|2000|p=252}}</ref>', None, 'page', '252', '', 1, ''),
    ('<ref name="IIHFHOF">{{harvnb|International Ice Hockey Federation}}</ref>', None, '', '', '', None, ''),
    ('<ref name="EncB47b"/>', '<ref name="EncB47b">{{Harvnb|Carder|1990|loc=§47, Section b.}}</ref>', 'at', '', '', None, ''),
    ('<ref name=mercenaries />', "<ref name=mercenaries>{{cite video game | title=Icewind Dale II | developer=[[Black Isle Studios]] | publisher=[[Interplay Entertainment]] | date=2002 | quote='''Narrator:''' Only a few small ships made it through to Targos, where my Uncle was watching from the upper reaches of the town. Many villagers were too busy repelling enemies at the palisade wall to notice a few sad, sorry stragglers make it into the port. The sun burned behind the horde and cast a cloak of shadows over the heart of Targos and all within. It was into this shadow that uncommon mercenaries were thrust from Captain Hedron's ship, the Wicked Wench. Like many other mercenaries in the town, these few had come from Luskan. Unlike the others, their journeys would take them far beyond the rude palisades and bloody fields that lay ahead of them...}}</ref>", 'quote', '', '', None, ''),
    ("<ref>{{cite video game | title=Icewind Dale II | developer=[[Black Isle Studios]] | publisher=[[Interplay Entertainment]] | date=2002 | quote='''Journal:''' We told Shawford that we'd pressured the Iron Collar band to get their worthless hides onto the Palisade, and he seemed surprised and grateful at our efforts. No sooner had he finished congratulating us when we heard an explosion from outside, and the Palisade was under attack![..]With aid from the Targos Guard, we managed to turn back the goblin attack on Targos and slaughter the goblin leaders. We should tell Shawford or Ulbrec of our success.}}</ref>", None, 'quote', '', '', None, ''),
    ('<ref name="AUTOCOURSE96"/>', '<ref name="AUTOCOURSE96">{{cite encyclopedia|last=Henry|first=Alan|editor=Henry, Alan|encyclopedia=AUTOCOURSE 1996-97|title =Formula 1 Review: Forti|year=1996|publisher=Hazleton Publishing Ltd|isbn=1-874557-91-8|page=92}}</ref>', 'page', '92', '', 1, ''),
    ('<ref>{{cite paper|title=Gunshot Wounds: 1. Bullets, Ballistics, and Mechanisms of Injury|author=Jeremy J. Hollerman, Martin L. Fackler, Douglas M. Coldwell, and Yoram Ben-Menachem|year=October 1990|publisher=American Journal of Roentgenology vol.155 no. 4|url=http://www.ajronline.org/content/155/4/685.full.pdf+html|pages= 685–690}}</ref>', None, 'pages', '', '685–690', 6, ''),
    ('<ref name= irishwoman />', '<ref name= irishwoman >{{Citation | last=Lombard | first=Jean | author-link=Jean Lombard | url= http://www.amazon.com/dp/1901658783 | title= Irish Woman in Czarist Russia | publisher=Ashfield Press | location= Dublin, Ireland | year=2010 | pages=105, 108 | ISBN=978-1-901658-78-1}}</ref>', 'pages', '', '105, 108', 2, ''),
    ('<ref name="The_Blessing_Way">{{cite episode| episodelink=The Blessing Way (The X-Files) | title=The Blessing Way | series=The X-Files | serieslink=The X-Files |credits = [[R.W. Goodwin]] (director); [[Chris Carter (screenwriter)|Chris Carter]] (writer) | network = [[Fox Broadcasting Company|Fox]] | season = 3 | number = 1 |airdate=September 22, 1995}}</ref>', None, '', '', '', None, ''),
    ('<ref name="Silly Love Songs">{{cite episode |title=Silly Love Songs|episodelink=Silly Love Songs (Glee)|series=Glee |series link=Glee (TV series) |credits=[[Tate Donovan]] (director), [[Ryan Murphy (writer)|Ryan Murphy]] (writer) |network=[[Fox Broadcasting Company|Fox]] |airdate=February 8, 2011 |season=2 |number=12}}</ref>', None, '', '', '', None, ''),
    ('<ref>{{cite report |title=Somalia: Verified IDP Sites in Bossaso as at April 2024 |publisher=UNHCR / CCCM Cluster Somalia |date=2024-04-23 |url=https://data.unhcr.org/en/documents/details/108143 |access-date=2025-10-13 |quote=22 IDP sites hosting 19,431 households (116,740 individuals).}}</ref>', None, 'quote', '', '', None, ''),
    ('<ref name = "Every Man for Himself">{{cite episode | title = Every Man for Himself | episode-link = Every Man for Himself (Lost) | series = Lost | series-link = Lost (2004 TV series) | credits = [[Stephen Williams (director)|Stephen Williams]] (director); [[Edward Kitsis]] & [[Adam Horowitz]] (writers) | network = ABC | airdate = 2006-10-25 | season = 3 | number = 4}}</ref>', None, '', '', '', None, ''),
    ('<ref>{{citation |title-link=:commons:File:April 1952 Boston and Maine Railroad timetable.pdf |date=April 27, 1952 |title=Passenger Train Schedules |publisher=Boston and Maine Railroad |via=Wikimedia Commons |pages=14, 15}}</ref>', None, 'pages', '', '14, 15', 2, ''),
    ('{{r|enc|page=339}}', None, 'page', '339', '', 1, ''),
    ('<ref name="CivicRecord1936"/>', '<ref name="CivicRecord1936">{{Citation |last1=Hosking |first1=P. |author2=Universal Publicity Company |title=The Official civic record of South Australia : centenary year, 1936 |date=1936 |publisher=Universal Publicity Company |url=http://nla.gov.au/nla.obj-11350397 |pages=201–203 |access-date=10 November 2017 |quote=The district was proclaimed a district council area on 20th July, 1853 [...] Included in the Municipality and District areas there is a population of approximately 5,800 persons, who are accommodated in 907 dwellings. The approximate area of the Corporation is 500 acres and the District 162,000 acres.}}</ref>', 'pages,quote', '', '201–203', 3, ''),
    ('<ref>{{cite magazine |last=Peacock |first=Gary |title=The Community of the Resurrection, at Mirfield, West Yorkshire |magazine=The Yorkshire Journal |issue=4 |page=6 |date=2014 |url=https://theyorkshirejournal.files.wordpress.com/2017/04/theyorkshirejournal-2014-04.pdf}}</ref>', None, 'page', '6', '', 1, ''),
    ('<ref>{{Citation|title=Kersten v. Van Grack, Axelson & Williamowsky, PC|date=July 7, 1992|url=https://scholar.google.com/scholar_case?case=14891219256467157803&q=Kersten+v.+Van+Grack,+Axelson+&+Williamowsky,+92+Md.+App.+466,+608+A.2d+1270+(Md.+App.+1992).&hl=en&as_sdt=800006|volume=608|pages=1270|access-date=2021-12-13}}</ref>', None, 'pages', '', '1270', 1, ''),
    ('<ref>{{Cite AV media |url=https://www.youtube.com/watch?v=L6aSKILcpM8&t=498s |title=Booster 9 Ready for Raptor Engine Testing {{!}} SpaceX Boca Chica |date=2023-07-23 |last=NASASpaceflight |time=8:18 |access-date=2025-03-01 |via=YouTube}}</ref>', None, 'other', '', '', None, ''),
    ('<ref name="needham"/>', '<ref name="needham">Needham, Joseph. (1987). \'\'Science and Civilization in China: Volume 5, Chemistry and Chemical Technology, Part 7, Military Technology; the Gunpowder Epic\'\'. Cambridge University Press. pp. 170-174.</ref>', 'pages', '', '170-174', 5, ''),
    ('<ref name="sidekick">Rothel.</ref>', None, '', '', '', None, ''),
    ('<ref>[http://www.bevoelkerungsschutz.admin.ch/internet/bs/de/home/themen/kgs/kgs_inventar.html Swiss inventory of cultural property of national and regional significance] 21.11.2008 version, {{de icon}} accessed 17-May-2010</ref>', None, '', '', '', None, ''),
    ('<ref>[http://news.yahoo.com/s/ap_travel/20080521/ap_tr_ge/travel_yesterday_s_places_endangered_places Threats to history seen in budget cuts, bulldozers - Yahoo! News<!-- Bot generated title -->]</ref>', None, '', '', '', None, ''),
    ('<ref name=RoM246>Record of Movements, p 246</ref>', None, 'page', '246', '', 1, ''),
    ('<ref>AfriqueJet.com: [http://www.afriquejet.com/news/africa-news/comoros-to-hold-legislative,-local-government-elections-on-2-august-2009061930055.html Comoros to hold legislative, local government elections on 2 August] (18 June 2009)</ref>', None, '', '', '', None, ''),
    ('<ref name=Raynolds1>Raynolds, R.G. 2002. Upper Cretaceous and Tertiary stratigraphy of the Denver Basin, Colorado. Rocky Mountain Geology, vol. 37, no. 2, p. 111-134.</ref>', None, 'pages', '', '111-134', 24, ''),
    ('<ref>[http://www.eecs.berkeley.edu/Faculty/Homepages/bajcsy.html Ruzena Bajcsy official page], EECS, College of Engineering, UC Berkeley, USA.</ref>', None, '', '', '', None, ''),
    ("<ref>[[Pope Vigilius]], ''Constitution of Pope Vigilius'', 553</ref>", None, '', '', '', None, ''),
    ("<ref>Julian Yates, ''Error, misuse, failure: object lessons from the English Renaissance'', U of Minnesota Press, 2002, ISBN 0-8166-3961-2, ISBN 978-0-8166-3961-8. [http://books.google.co.uk/books?id=hzfCeZspGHIC&pg=PA187&dq=Harvington+hall p. 187]</ref>", None, 'page', '187', '', 1, ''),
    ('<ref>http://twitter.com/missnatalienunn/status/289488193986887680/photo/1</ref>', None, '', '', '', None, ''),
    ('<ref>Official municipal journal of the city of Lyon for discussions that have authorized these actions.</ref>', None, '', '', '', None, ''),
    ('<ref name="taylor146-148"/>', '<ref name="taylor146-148">Taylor, Peter (1999). \'\'Loyalists\'\'. London: Bloomsbury Publishing Plc. pp.146-148</ref>', 'pages', '', '146-148', 3, ''),
    ('<ref name="tatarinov"/>', '<ref name="tatarinov">[http://tatarinov.tv/%D0%B1%D0%B8%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8F/ Biography at the official Tatarinov site]{{ref-ru}}</ref>', '', '', '', None, ''),
    ('<ref>http://www.sunwingtravelgroup.com/en/Our-Brands/Tour-Operations/Signature-Vacations.aspx</ref>', None, '', '', '', None, ''),
    ("<ref>Jon Ploug Jørgensen, ''The taming of the  aristoi - an ancient Greek civilizing process?'' [[History of the Human Sciences]]: July 2014 vol. 27 no. 3, pg 45</ref>", None, 'page', '45', '', 1, ''),
    ('<ref name="Howlett/liner notes" />', '<ref name="Howlett/liner notes">Kevin Howlett, booklet accompanying \'\'Living in the Material World\'\' reissue (EMI Records, 2006; produced by Dhani & Olivia Harrison).</ref>', '', '', '', None, ''),
    ('<ref name="Helmens2015"/>', None, '', '', '', None, ''),
    ("<ref>''League of Nations Treaty Series'', vol. 7, pp. 78–83.</ref>", None, 'pages', '', '78–83', 6, ''),
    ('<ref name="u-14"/>', None, '', '', '', None, ''),
    ('<ref>[https://www.zdnet.com/home-and-office/networking/internode-broadband-to-rural-sa-rescue/ "Zdnet Internode"] Retrieved on 25 September 2008.</ref>', None, '', '', '', None, ''),
    ('<ref name="CofT">Peter Bouckaert. \'\'Center of the Storm: A Case Study of Human Rights Abuses in Hebron District.\'\' Human Rights Watch, 2001. {{ISBN|1-56432-260-2}} and {{ISBN|978-1-56432-260-9}} pp. 109-110</ref>', None, 'pages', '', '109-110', 2, ''),
    ('<ref name="r14"/>', None, '', '', '', None, ''),
    ('<ref>[https://www.bundestag.de/resource/blob/878348/b21e5621b2f3de04e328535bd589e151/mitglieder_bv_2022-data.pdf 17th Federal Convention, 13 February 2022, List of Members] [[Bundestag]].</ref>', None, '', '', '', None, ''),
    ('<ref>[http://eldia.com.do/luis-miguel-se-lleva-todo-y-mas-en-el-festival-de-vina/ Luis Miguel takes all and more at the Festival of Viña]</ref>', None, '', '', '', None, ''),
    ('<ref name=ODOT1926_map/>', None, '', '', '', None, ''),
    ('<ref name=":4">\'\'Keesing\'s Contemporary Archives 1950–1952\'\', page 11076</ref>', None, 'page', '11076', '', 1, ''),
    ('<ref name="Henkel"/>', '<ref name="Henkel">Henkel, Steve: \'\'The Sailor\'s Book of Small Cruising Sailboats\'\', page 204. [[International Marine]]/[[McGraw-Hill]], 2010. {{ISBN|978-0-07-163652-0}}</ref>', 'page', '204', '', 1, ''),
    ('<ref name=kold>{{cite web|access-date=2023-04-09 |date=20 September 2021 |language=en |title=Tucson astronomer discovers comet |url=https://www.kold.com/2021/09/20/tucson-astronomer-discovers-new-comet/ |website=kold.com}}<!-- auto-translated from French by Module:CS1 translator --></ref>', None, '', '', '', None, ''),
    ("<ref>''RPM The Programmers WEEKLY'' Volume 19 No. 9 April 14, 1973 - [https://worldradiohistory.com/CANADA/RPM/70s/1973/RPM-1973-04-14.pdf Page 29 The Programmers ''CAMPUS ADDITIONS'' ''LPs RADIO BROCKIST. CATHARINES'']</ref>", None, 'page', '29', '', 1, ''),
    ('<ref name = "Hartmann1" />{{rp|13}}', '<ref name = "Hartmann1">{{citation\r\n|last1=Hartmann\r\n|first1=Gérard\r\n|title=Les réalisations de la SNCASE\r\n|url=http://www.hydroretro.net/etudegh/sncase.pdf\r\n|format=PDF\r\n|accessdate=2009-07-15\r\n|date=2005-01-05\r\n|language=French\r\n|quote=Alors qu’on ne sait pas très clairement si les sociétés nationales sont des « usines de production de guerre » sans indépendance et sans bureau d\'études, la SNCASE est officiellement formée le 1er février 1937.}}</ref>', 'page,quote', '13', '', 1, ''),
    ('<ref name = "Hartmann1" />{{rp|13}}', '<ref name = "Hartmann1">{{citation\r\n|last1=Hartmann\r\n|first1=Gérard\r\n|title=Les réalisations de la SNCASE\r\n|url=http://www.hydroretro.net/etudegh/sncase.pdf\r\n|format=PDF\r\n|accessdate=2009-07-15\r\n|date=2005-01-05\r\n|language=French\r\n|quote=Alors qu’on ne sait pas très clairement si les sociétés nationales sont des « usines de production de guerre » sans indépendance et sans bureau d\'études, la SNCASE est officiellement formée le 1er février 1937.}}</ref>', 'page,quote', '13', '', 1, ''),
    ('<ref name="Majumdar" />{{rp|100}}', '<ref name="Majumdar">{{cite book | chapter=Hemu: A forgotten Hindu Hero | url=http://books.google.co.in/books?id=0Q5uAAAAMAAJ | title=[[The History and Culture of the Indian People]] Vol 7: The Mughal Empire | publisher=Bharatiya Vidya Bhavan | last=Majumdar | first=Ramesh Chandra | authorlink=Ramesh Chandra Majumdar | year=1984}}</ref>', 'chapter,page', '100', '', 1, ''),
    ('<ref name="parshu" />{{rp|65}}', '<ref name=parshu>Dr. Parshu Ram Gupt, "Rashtra Gaurav Samrat Hem Chandra Vikramaditya", Gorakhpur</ref>{{rp|45}}', 'page', '65', '', 1, ''),
    ('<ref name=Crovetto>{{citation\r\n| chapter=Ananda Marga, Prout, and the Use of Force\r\n| last=Crovetto\r\n| first=Helen\r\n| title=Violence and New Religious Movements\r\n| editor-last=Lewis\r\n| editor-first=James R.\r\n| editorlink = James R. Lewis (scholar)\r\n| year=2011\r\n| publisher=\r\n[[Oxford University Press]]| ISBN=9780199735631\r\n| pages=249&ndash;274\r\n}}</ref>{{rp|257}}', None, 'chapter,page,pages', '257', '249&ndash;274', 1, "pages value differs (gold='249–274')"),
    ('<ref name="Brandt" />{{Rp|293–294}}', '<ref name="Brandt">\r\n{{cite book | last = Brandt | first = Allan M. | title = The Cigarette Century: the Rise, Fall and Deadly Persistence of the Product That Defined America | publisher = Basic Books, a member of the Perseus Books Group | location = New York | year = 2007 | isbn = 978-0-465-07047-3 }}</ref>{{Rp|251}}', 'pages', '', '293–294', 2, ''),
    ('<ref name="Pribich"/>{{rp|280–281}}', '<ref name="Pribich">{{cite book\r\n  | last = Pribich\r\n  | first = Kurt\r\n  | title = Logbuch der Pfadfinderverbände in Österreich\r\n  | publisher = Pfadfinder-Gilde-Österreichs\r\n  | year = 2004\r\n  | location = Vienna\r\n  | language = German}}</ref>{{rp|280}}', 'pages', '', '280–281', 2, ''),
    ('<ref name="Wuthnow2019" />{{rp|32}}', '<ref name="Wuthnow2019">{{cite book |url=https://inss.ndu.edu/Portals/82/China%20SP%2014%20Final%20for%20Web.pdf |title=China\'s Other Army: The People\'s Armed Police in an Era of Reform |last=Wuthnow |first=Joel |date=16 April 2019 |publisher=Institute for National Strategic Studies |location=Washington |access-date=3 October 2019 |archive-date=4 July 2020 |archive-url=https://web.archive.org/web/20200704193636/https://inss.ndu.edu/Portals/82/China%20SP%2014%20Final%20for%20Web.pdf |url-status=live}}</ref>{{rp|10,32}}', 'page', '32', '', 1, ''),
    ('<ref name="blair-tpi-40">{{cite book|url=http://www.gutenberg.org/ebooks/30253|title=The Philippine Islands, 1493–1898|publisher=[[Arthur H. Clark Company]]|others=Historical introduction and additional notes by [[Edward Gaylord Bourne|Edward Gaylord BOURNE]]|year=1906|isbn=978-0559361821|editor1-last=BLAIR|editor1-first=Emma Helen|editor1-link=Emma Helen Blair|volume=40 of 55 (1690–1691)|location=Cleveland, Ohio|oclc=769945730|quote=<span style="font-family:Times;font-size:95%">Explorations by early navigators, descriptions of the islands and their peoples, their history and records of the catholic missions, as related in contemporaneous books and manuscripts, showing the political, economic, commercial and religious conditions of those islands from their earliest relations with European nations to the close of the nineteenth century.</span>|editor2-last=ROBERTSON|editor2-first=James Alexander|editor2-link=James Alexander Robertson|name-list-style=amp}}</ref>{{rp|page=218}}', None, 'page,quote', '218', '', 1, ''),
    ('<ref name="leyes-vi">{{cite book |editor1-last    = de León Pinelo |editor1-first   = Antonio Rodríguez |editor1-link    = Antonio de León Pinelo |editor2-last    = de Solórzano Pereira |editor2-first   = Juan |editor2-link    = :es:Juan de Solórzano Pereira |title           = Recopilación de Leyes de los Reynos de las Indias |language        = es |url             = http://www.congreso.gob.pe/ntley/libroIndia.asp?wLibro=Sexto |format          = pdf |volume          = Libro Sexto |year            = 1680 |quote           = \'\'\'Títulos\'\'\': \'\'\'i\'\'\' De los Indios. \'\'\'ii\'\'\' De la libertad de los Indios. \'\'\'iii\'\'\' De las Reducciones, y Pueblos de Indios. \'\'\'iv\'\'\' De las caxas de censos, y bienes de Comunidad, y su administracion.   \'\'\'v\'\'\' De los tributos, y tassas de los Indios. \'\'\'vi\'\'\' De los Protectores de Indios. \'\'\'vii\'\'\' De los Caciques. \'\'\'viii\'\'\' De los repastimientos, encomiendas, y pensiones de Indios, y calidades de los titulos. \'\'\'ix\'\'\' De los Encomenderos de Indios. \'\'\'x\'\'\' De el buen tratamiento de los Indios. \'\'\'xi\'\'\' De la sucession de encomiendas, entretenimientos, y ayudas de costa. \'\'\'xii\'\'\' Del servicio personal. \'\'\'xiii\'\'\' Del servicio en chacras, viñas, olivares, obrajes, ingenios, perlas, tambos, requas, carreterias, casas, ganados, y bogas. \'\'\'xiv\'\'\' Del servicio en coca, y añir. \'\'\'xv\'\'\' Del servicio en minas. \'\'\'xvi\'\'\' De los Indios de Chile. \'\'\'xvii\'\'\' De los Indios de Tucuman, Paraguay, y Rio de la Plata. \'\'\'xviii\'\'\' De los Sangleyes. \'\'\'xix\'\'\' De las confirmaciones de encomiendas, pensiones, rentas, y situaciones. |name-list-style = amp |access-date     = 8 November 2014 |archive-date    = 27 May 2011 |archive-url     = https://web.archive.org/web/20110527033419/http://www.congreso.gob.pe/ntley/libroIndia.asp?wLibro=Sexto |url-status      = dead}}</ref>{{rp|at=tit. VII, ley xvi}}', None, 'quote', '', '', None, ''),
    ('<ref name=":1">{{Cite web|url=http://www.virtualmuseum.ca/sgc-cms/histoires_de_chez_nous-community_stories/pm_v2.php?id=story_line&lg=English&fl=0&ex=00000642&sl=5191&pos=1|title=The History of Shipbuilding in Marystown, NL, Canada|website=Community Stories|publisher=VMC (VirtualMuseum.ca)|at=5 - Marystown Co-operative Enterprise (Minesweepers)|access-date=20 March 2020}}</ref>{{Rp|2}}', None, 'at,page', '2', '', 1, ''),
    ('<ref name="Brown2023"/>{{rp|2}}', None, 'page', '2', '', 1, ''),
    ('<ref name="Ackerman" />{{rp|351}}', '<ref name="Ackerman">{{cite book | title=Lake Placid Club. An Illustrated History | publisher=Lake Placid Education Foundation | author=Ackerman, David | year=1998 | location=Lake Placid, New York | pages=367–368 | isbn=0-9665875-0-2}}</ref>', 'page,pages', '351', '367–368', 1, ''),
    ('<ref name="Raising Kane"/>{{Rp|20}}', '<ref name="Raising Kane">{{cite book |last1=Kael |first1=Pauline |author-link1=Pauline Kael |last2=Welles |first2=Orson |author-link2=Orson Welles |last3=Mankiewicz |first3=Herman J. |author-link3=Herman J. Mankiewicz |year=1971 |title=The Citizen Kane Book |chapter=Raising Kane by Pauline Kael |chapter-url=http://www.paulrossen.com/paulinekael/raisingkane.html |location=Boston |publisher=[[Little, Brown and Company]] |pages=1–84 |oclc=301527105 |access-date=December 4, 2014 |archive-date=June 20, 2006 |archive-url=https://web.archive.org/web/20060620060353/http://www.paulrossen.com/paulinekael/raisingkane.html |url-status=live }}</ref>', 'chapter,page,pages', '20', '1–84', 1, ''),
    ('<ref name="Brady"/>{{Rp|553–554}}', '<ref name="Brady">{{cite book |last=Brady |first=Frank |author-link=Frank Brady (writer) |title=Citizen Welles: A Biography of Orson Welles |publisher=[[Charles Scribner\'s Sons]] |location=New York |date=1989 |isbn=0-385-26759-2 |url=https://archive.org/details/citizenwellesbio00brad }}</ref>{{Rp|234}}', 'pages', '', '553–554', 2, ''),
    ('{{Sfn|Pascual|Ortiz-Jaureguizar|2007|loc=fig. 11}}', None, 'at', '', '', None, ''),
    ('{{Sfn|Gurovich|2008|loc=table 2}}', None, 'at', '', '', None, ''),
    ('{{sfn|Edmonds|1948|pp=200–201 & sketch 19}}', None, 'pages', '', '200–201 & sketch 19', 2, ''),
    ('{{sfn|Schweikert|2001|pp=504–507}}', None, 'pages', '', '504–507', 4, ''),
    ('{{sfn|Ceceñas}}', None, '', '', '', None, ''),
    ('{{sfn|Pierce|1895|p=249}}', None, 'page', '249', '', 1, ''),
    ('{{sfn|Dapin|2008|p=198}}', None, 'page', '198', '', 1, ''),
    ('{{sfn|NED NGC 3344}}', None, '', '', '', None, ''),
    ('{{Sfn|Hay|1997|p=32}}', None, 'page', '32', '', 1, ''),
    ('{{sfn|Martinović|2003|loc=Opšte napomene}}', None, 'at', '', '', None, ''),
    ('{{sfn|Martinović|2003|loc=ch. 1}}', None, 'at', '', '', None, ''),
    ('{{sfn|Palevsky|2005|pp=2–3}}', None, 'pages', '', '2–3', 2, ''),
    ('{{sfn|Thomas|1998|p=320}}', None, 'page', '320', '', 1, ''),
    ('{{sfn|Halm|1991|pp=370–371}}', None, 'pages', '', '370–371', 2, ''),
    ('{{sfn|Мясников|2014}}', None, '', '', '', None, ''),]


def _flat(wt, md):
    if md:
        resolved = resolve_references([_ref_from_wikitext(md), _ref_from_wikitext(wt)])[1]
        return {k: v for k, v in resolved.items() if k in LOCATOR_COLS}
    return dict(parse(wt)["locators"])


def _norm(s):
    return (s or "").strip().replace("\u2013", "-").replace("\u2014", "-").replace("\u2212", "-")


def test_golden():
    for i, (wt, md, types, page, pages, located, note) in enumerate(GOLD):
        flat = _flat(wt, md)
        got = {CANON.get(k, "other") for k in flat}
        exp = set(types.split(",")) if types else set()
        assert got == exp, f"row{i} types {sorted(got)} != {sorted(exp)} (locators={flat})"
        if page:
            assert _norm(flat.get("page") or flat.get("p")) == _norm(page), f"row{i} page"
        if pages:
            assert _norm(flat.get("pages") or flat.get("pp")) == _norm(pages), f"row{i} pages"
        got_located = compute_located_pages(flat)
        assert got_located == located, f"row{i} located_pages {got_located!r} != {located!r} ({note})"
